enable-magisk-update = true # set this to false if you do not want to receive up

[Music-RVX]
app-name = "Music"
build-mode = "both"
version = "7.16.52"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v2.232.0-dev.1"
integrations-version = "v0.159.0-dev.1"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = ""
included-patches = "'Custom branding icon for YouTube Music' 'Custom branding name YouTube Music' 'Amoled' 'Bitrate default value' 'Certificate spoof' 'Change start page' 'Disable auto captions' 'Disable dislike redirection' 'Enable debug logging' 'Enable landscape mode' 'Enable minimized playback' 'Enable opus codec' 'Flyout menu components' 'GmsCore support' 'Hide account components' 'Hide action bar components' 'Hide ads' 'Hide double tap overlay filter' 'Hide layout components' 'Hide overlay filter' 'Hide player overlay filter' 'Navigation bar components' 'Remove viewer discretion dialog' 'Player components' 'Replace cast button' 'Restore old style library shelf' 'Return YouTube Dislike' 'Sanitize sharing links' 'Settings' 'SponsorBlock' 'Spoof app version' 'Translations' 'Video playback'"
arch = "arm64-v8a"

[YouTube-RVX]
app-name = "YouTube"
build-mode = "both"
version = "19.16.39"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v2.232.0-dev.1"
integrations-version = "v0.159.0-dev.1"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
excluded-patches = ""
included-patches = "'Shorts overlay buttons' 'Custom branding icon for YouTube' 'Custom branding name YouTube' 'Add splash animation' 'Alternative thumbnails' 'Disable splash animation'"
arch = "arm64-v8a"

[Reddit]
app-name = "Reddit"
version = "2024.17.0"
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
patches-version = "v2.232.0-dev.1"
integrations-version = "v0.159.0-dev.1"
included-patches = "'Disable screenshot popup' 'Hide ads' 'Hide navigation buttons' 'Hide recently visited shelf' 'Open links directly' 'Open links externally' 'Premium icon' 'Remove subreddit dialog' 'Sanitize sharing links' 'Settings'"
rv-brand = "RVX"
arch = "arm64-v8a"

[twitter-non-monet]
build-mode = "apk"
version = "10.49.0-release.0"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
patches-version = "v1.42.1"
integrations-version = "v1.31.2"
rv-brand = "Piko Patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
included-patches = ""
excluded-patches = "'Dynamic color'"
arch = "arm64-v8a"
